const gulp = require('gulp');
const fs = require('fs');
const path = require('path');
const chalk = require('chalk');
const glob = require('glob');

gulp.task('icons', (done) => {
	const iconsDir = './icons';

	glob('**/*.svg', { cwd: iconsDir }, (err, files) => {
		if (err) {
			console.error(chalk.red('Error reading SVG files:', err));
			done(err);
			return;
		}

		const iconData = {};

		files.forEach((file) => {
			const iconName = path.basename(file, '.svg');
			let multicolor = iconName.toLowerCase().includes('multicolor');

			if (!multicolor) {
				const iconContents = fs.readFileSync(
					path.resolve(`icons${path.sep}${file}`),
					'utf8'
				);

				const colorValues = iconContents.match(/[":=]#[0-9a-zA-Z]*/g);

				if (colorValues) {
					const uniqueColorValues = [...new Set(colorValues)];

					if (uniqueColorValues.length > 1) {
						multicolor = true;
					}
				}
			}

			iconData[iconName] = { multicolor };
		});

		const scssOutput = `// Note: do not edit this file directly. All content is generated automatically via the 'gulp icons' task.\n\n${generateSCSS(iconData)}`;

		fs.writeFile(path.join(iconsDir, '_icons.scss'), scssOutput, (err) => {
			if (err) {
				console.error(chalk.red('Error writing SCSS file:', err));

				done(err);
				return;
			}

			console.log(chalk.green('SCSS file generated successfully!'));
			done();
		});
	});
});

function generateSCSS(iconData) {
	let scssOutput = '$icons: (\n';

	for (const iconName in iconData) {
		if (iconData.hasOwnProperty(iconName)) {
			scssOutput += `\t${iconName.replace('-multicolor', '')}: (\n`;
			scssOutput += `\t\tmulticolor: ${iconData[iconName].multicolor},\n`;
			scssOutput += `\t),\n`;
		}
	}

	scssOutput += `);`;

	return scssOutput;
}
